[package]
name = "awesome_axum_responses"
version = "0.1.0"
edition = "2024"
description = "A collection of axum response wrappers"
repository = "https://github.com/DragonFoxCollective/awesome_axum_responses"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { version = "1.0.102", optional = true }
askama = { version = "0.16.0", optional = true }
axum = "0.8.9"
tracing = { version = "0.1.44", optional = true }

[features]
default = []
anyhow = ["dep:anyhow", "dep:tracing"]
askama = ["anyhow", "dep:askama"]
